# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
use_frameworks!

target ‘Demo’ do

pod ‘Firebase/Core’
pod 'Firebase/Auth'
pod 'Firebase/Database'

end